### ISSUE TITLE
wlroots dependency mismatch with the main wayfire git

### ISSUE THREAD

**Issue by aMir733** [AhoyISki/wayfire-firedecor#4]
firedecor requires wlroots >=16 but the main wayfire git requires wlroots [<16](https://github.com/WayfireWM/wayfire/commit/bb1a47d645a5e36098ce1d92e0fe3302e97547fe).

EDIT: [This](https://github.com/WayfireWM/wayfire/commit/df6691b3ad0ea8c0cdd2e33579bf9089c6873b93) is the commit.

**Comment by AhoyISki** [comment]
Closing with 71c69b7b33ade91dc87edc4b07036fe95ab6010c
